package com.fdilke.varsymm

import org.scalatest.FunSpec
import org.scalatest.Matchers._

class GroupTest extends FunSpec {
  describe("Built-in methods for Groups") {
    it("can calculate the subgroup generated by a subset") {
      val group: Group[Permutation] =
        Permutation.group(3)

      val transposition = Permutation(0, 2, 1)

      group.generateSubgroup() shouldBe group.trivialSubgroup

      group.generateSubgroup(
        transposition
      ).elements.toSet shouldBe Set(
        group.unit,
        transposition
      )

      val rotation = Permutation(1, 2, 0)

      group.generateSubgroup(
        transposition,
        rotation
      ).elements.toSet shouldBe
        group.elements.toSet
    }
  }
}
